### ISSUE TITLE
Fix / Feature angles

### ISSUE THREAD

**Issue by NicolasDelahaigue** [Indaym/Web-Indaym#11]
### Problème
Dans le panel de droite les angles sont en radian.

### Solutions
1 - Mettre les angles en degrés (Fix)
2 - Offrir l'options de mettre en radian ou en degrés via deux boutons radio (Feature)

**Comment by djavrell** [comment]
je ne pense pas que ce serait si long que ca de mettre l'option 2 en place, après je sais pas ce que ca change au niveau e l'interface

**Comment by NicolasDelahaigue** [comment]
Rien de spécial juste deux boutons radio et puis faut que je regarde si threejs à quelque chose d'intégré pour ça. 
Si c'est pas le cas alors le two ways binding va me casser les couilles comme toujours.

**Comment by djavrell** [comment]
ok je vois, comme vous le santé alors

**Comment by NicolasDelahaigue** [comment]
Je pense que je vais mettre la deux en place mais je vais me concentrer sur mes objectifs sur le prochain suivi donc il y a des chances que ce ne soit pas implémenté avant très longtemps

**Comment by NicolasDelahaigue** [comment]
Fixed
