### ISSUE TITLE
migration pull request

### ISSUE THREAD

**Issue by djavrell** [Indaym/Web-Indaym#2]
Pensez à re-faire vos pull request ici s'il vous plait

**Comment by NicolasDelahaigue** [comment]
Tu veux que l'on transfert toutes les merge requests closed ici ?

**Comment by djavrell** [comment]
nan, celles qui sont en cours ...

**Comment by NicolasDelahaigue** [comment]
Ah oui mais il y a aucunes pull request  d'ouverte donc c'est pas refaire mais faire si vous en avez
Désolé je chipote mais ça change tout le sens de ton message

**Comment by djavrell** [comment]
comme si c'était pas compréhensible, mais bon, vu qu'elles sont sensé être faites sur l'autre déjà ...

**Comment by tokiplow** [comment]
Hum... Du coup, je ferais plein de pull request quand je ferais des trucs !

**Comment by djavrell** [comment]
fait déjà des pull requests :unamused:
