### ISSUE TITLE
channel slack

### ISSUE THREAD

**Issue by djavrell** [Indaym/Web-Indaym#4]
je rappelle les choix qui sont proposé pour la création des channels d'intégration

* 2 channels au total
    * chan 1: commits/Tags
    * chan 2: pull-request/issues
* 4 channels au total
   * chan 1: commits/tags/comments
   * chan 2: pulls-request/build travis/issues
   > ce groupe de channels par dépo, donc 2 à chaque fois

pour le moment, vous partez plus sur la 2ème options

des choses à dire avant que je le met en place ?

**Comment by tokiplow** [comment]
Je pense que c'est bon. 
On en rechargera si des choses viennent à nous gêner.

**Comment by NicolasDelahaigue** [comment]
Les absents ont toujours tord tu peux attendre que les autres répondent mais dans tous les cas la majorité est pour le 2 donc je pense que tu peux close cette issue et faire la modification

**Comment by djavrell** [comment]
pour le coup, j'aimerais avoir l'avis de tout le monde

**Comment by NicolasDelahaigue** [comment]
As you want :)

**Comment by djavrell** [comment]
si j'ai bien compris, je peux me gratter pour avoir des gens autre que @NicolasDelahaigue ou @tokiplow qui réponde ici

du coup je fais ce qui est dit asap

**Comment by tokiplow** [comment]
:)

**Comment by djavrell** [comment]
bon bah normalement c'est bon :+1: 

à voir si doit y'avoir des ajustement à faire plus tard

(l'intégration me donne pas masse marge de manœuvre :disappointed:  )
