### ISSUE TITLE
pre-commit hook

### ISSUE THREAD

**Issue by djavrell** [Indaym/Web-Indaym#5]
Petite question,

est-ce que a vous dit que je mets en place en système de hook pour executer le linter avant de commit ?

pour info, voilà le tool:
> https://github.com/nlf/precommit-hook

**Comment by NicolasDelahaigue** [comment]
Questions :
Est-ce que ça bloquera le commit en cas d'échec ?

### Avantage
- ça permet de garder un code propre

### Inconvénient 
- si tu dois passer 30 minutes à refactoriser ton code parce que tu as mal nommé un variable ou c'est mal identité on risque de perdre du temps et surtout démotiver les gens à bosser si il doivent passer trop de temps dessus

**Comment by tokiplow** [comment]
Je suis contre. On a déjà pas mal de truc en place pour travailler, rappelons qu'après L'EIP, ce projet sera abandonner probablement.

**Comment by djavrell** [comment]
Ok, c'est bien pour ca que je demande

Après,  la quantité de chose mise en place,  perso je m'en fou,  ca fait une montée de compétences sur le sujet,  donc bon,  je m'en fou

**Comment by NicolasDelahaigue** [comment]
Peut être intéressant sur une pull request  par contre
Car le merge de code doit se faire proprement

**Comment by djavrell** [comment]
pour les PR, c'est travis qui va le faire

par contre, je peux limiter l’exécuter que sur les branches master et develop


mais de toute façon, les 3 testes sont exécuter, pas de soucie à ce niveau

**Comment by NicolasDelahaigue** [comment]
J'imagine que tu peux pas choisir quel script tu mets sur quel branche ?
Au pire on peut les exécuter à la mano si on veut faire les tests nous même

**Comment by djavrell** [comment]
avec un peu de shell oui
sinon, je choisie les branches ou Travis va s'executer (vien des regex dans le fichier de conf)

**Comment by djavrell** [comment]
bon, pour les hooks, je les fais âs

et pour travis, il ne s'éxecute que sur les branches dev et master

du coup je close l'issue
