### ISSUE TITLE
Trouver Gitlab

### ISSUE THREAD

**Issue by NicolasDelahaigue** [Indaym/Web-Indaym#9]
On va jouer à un jeu si vous voulez bien.

Les consignes sont simples : Trouvez gitlab dans les fichiers.

Personnellement j'en ai trouvé 2, dans le Readme de Web-Indaym et Back-Indaym.

https://raw.githubusercontent.com/Indaym/Web-Indaym/develop/README.md

Je corrige ça asap. Je laisse l'issue ouverte au cas où vous en trouvez d'autres.

**Comment by djavrell** [comment]
man grep dude :heart:

**Comment by NicolasDelahaigue** [comment]
Wala c'est dur ! Alors windows + R, cmd, Entrée, grep -rn gitlab

> 'grep' n'est pas reconnu en tant que commande interne ou externe, un programme exécutable ou un fichier de commande

Sniff ça marche pas :'(

**Comment by djavrell** [comment]
passe sur un vrai OS, à la limite sur un vrai terminal :neutral_face: #babun

:heart:

**Comment by NicolasDelahaigue** [comment]
ahah ^^ Tkt je ferais ça plus tard :) Cette issue me sert de post-it au passage :P

**Comment by NicolasDelahaigue** [comment]
Problème réglé en attente de ta review.

**Comment by NicolasDelahaigue** [comment]
Review effectué par Florent, du coup je close.

**Comment by tokiplow** [comment]
Et à 4h30 du matin...
